---
version: 2.1
#################################
## Super Linter GitHub Actions ##
#################################
name: Super Linter

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

orbs:
  github-super-linter: circleci/github-super-linter@1.0
workflows:
  lint-code:
    jobs:
      - github-super-linter/lint
